yml-org/YMatterType

- Sources/YMatterType/Typography/FontRepresentable.swift
- Tests/YMatterTypeTests/Typography/FontRepresentableTests.swift
In working on my design systems tutorial I realized I needed access to an internal function.
Mark the function in question as public.
Ticket: [CM-735](https://ymedialabs.atlassian.net/browse/CM-735)
* mark one internal func in FontRepresentable as public
* add documentation comments
* add a comprehensive unit test
> [CM-735] Mark isBoldTextEnabled public

- YMatterType.podspec
Cocoapods integration was pointing to the wrong repo!
Point the podspec to this repo
Fix the podspec file
I removed the cocoapods entry for YMatterType until we get this fixed (it was linking YCoreUI).
> [CM-740] fix podspec

- Sources/YMatterType/Elements/TypographyTextView.swift
- Tests/YMatterTypeTests/Elements/TypographyTextViewTests.swift
Using latest Xcode 14 beta, unit tests for `TypographyTextView` would fail when targeting iOS 16.
Fix our text view so that it sizes itself properly (as a multiple of line height) under iOS 16
* iOS 16-only change to `TypographyTextView`
* slight change to a unit test
Starting with iOS 16, `UITextView` uses TextKit 2 text layout manager to render text view content. For whatever reason, when rendered in this manner the text view's intrinsic content size does not reflect the number of lines despite our use of attributed text attributes to set line height. However, there is a work around to get the text view to render using the legacy TextKit 1 layout manager. Using the original layout manager the text view's have the expected intrinsic content size.
99.3% when testing iOS 15, 100% when …
> Fix iOS 16 UITextView intrinsicContentSize bug

- README.md
- Sources/YMatterType/Typography/FontFamily.swift
- Sources/YMatterType/Typography/FontInfo.swift
- Sources/YMatterType/Typography/SystemFontInfo.swift
- Sources/YMatterType/Typography/Typography+SFPro.swift
- Sources/YMatterType/Typography/Typography.swift
- Sources/YMatterType/Typography/TypographyLayout.swift
- Tests/YMatterTypeTests/Elements/TypographyLabelTests.swift
- Tests/YMatterTypeTests/Elements/TypographyTextViewTests.swift
- Tests/YMatterTypeTests/Typography/FontFamilyTests.swift
- Tests/YMatterTypeTests/Typography/SystemFontInfoTests.swift
- Tests/YMatterTypeTests/Typography/Typography+FontTests.swift
- Tests/YMatterTypeTests/Typography/Typography+SFProTests.swift
Naming is hard! I think `FontFamily` is a better name than `FontRepresentable` that we originally used. It doesn't represent a font, it represents an entire family of fonts.
Rename `FontRepresentable` to `FontFamily`
* Replace all instances (including in README)
* Add a `typealias` for backwards compatibility, but deprecate it so folks know to rename
Code and documentation coverage were both unchanged. Just renaming.
> Rename `FontRepresentable` to `FontFamily`

- README.md
- Sources/YMatterType/Typography/FontFamily.swift
- Sources/YMatterType/Typography/SystemFontFamily.swift
- Sources/YMatterType/Typography/Typography+System.swift
- Tests/YMatterTypeTests/Typography/FontFamilyTests.swift
- Tests/YMatterTypeTests/Typography/SystemFontFamilyTests.swift
Naming is hard! This PR is part of a series of renaming PR's.
Rename `SystemFontInfo` to `SystemFontFamily` because it conforms to the `FontFamily` protocol (also it's not info about any single font but about a family of fonts)
* Replace all instances of `SystemFontInfo` with the new name
* For backwards compatibility creates a `typealias` from the original name (but mark it as deprecated)
* Rename `FontInfo.system` to `Typography.systemFamily` which is more in line with how other concrete implementations of `FontFamily` have been organized.
Coverage was not materially changed by this renaming operation.
> Rename SystemFontInfo to SystemFontFamily

- Sources/YMatterType/Typography/Typography.swift
- Tests/YMatterTypeTests/Typography/TypogaphyTests.swift
To better support machine-generated instantiation of Typography objects (i.e. export from Figma tokens via a plugin) we need a way to map from the family name strings exported as tokens to a potentially custom `FontFamily` that would be project specific.
Add the ability to alter the factory that Typography uses by default to map from a font family name (String) to a `FontFamily` object.
* add static `factory` variable to Typography
* modify the convenience initializer to use the factory to map family name + font style to a `FontFamily`
> Allow user to change Typography’s default font factory

- README.md
- Sources/YMatterType/Typography/FontFamily/FontFamily.swift
- Tests/YMatterTypeTests/Typography/FontFamily/FontFamilyTests.swift
- Tests/YMatterTypeTests/Typography/TypogaphyTests.swift
- Tests/YMatterTypeTests/Typography/Typography+FontTests.swift
We don't always have all 9 supported font weights for a given font family (some times they don't even exist, other times we don't want to bundle font weights we don't need). We should make it easier to specify what weights we _do_ support.
Add a property to indicate which weights a font family supports.
* Add `supportedWeights` property to `FontFamily` protocol
* default implementation is to return all weights
* revise `accessibilityWeight(for:)` func to iterate through supported weights and return the next heavier weight (if any), otherwise returns the heaviest weight
* unit tests for new functionality
> Add supportedWeights property

- Package.swift
- README.md
- Sources/YMatterType/Elements/TypographyButton.swift
- Sources/YMatterType/Elements/TypographyLabel.swift
- Sources/YMatterType/Elements/TypographyTextField.swift
- Sources/YMatterType/Extensions/UIKit/NSParagraphStyle+lineSpacing.swift
- Sources/YMatterType/Typography/FontFamily/DefaultFontFamily.swift
- Sources/YMatterType/Typography/FontFamily/FontFamily.swift
- Sources/YMatterType/Typography/FontFamily/SystemFontFamily.swift
- Sources/YMatterType/Typography/Typography+System.swift
- Sources/YMatterType/Typography/Typography.swift
- Sources/YMatterType/Typography/TypographyLayout.swift
- Tests/YMatterTypeTests/Elements/ElementFontAdjustedTests.swift
- Tests/YMatterTypeTests/Elements/TypographyButtonTests.swift
- Tests/YMatterTypeTests/Elements/TypographyLabelTests.swift
- Tests/YMatterTypeTests/Elements/TypographyTextFieldTests.swift
- Tests/YMatterTypeTests/Elements/TypographyTextViewTests.swift
- Tests/YMatterTypeTests/Extensions/Foundation/NSAttributedString+textCaseTests.swift
- Tests/YMatterTypeTests/Extensions/UIKit/UITraitCollection+traits.swift
- Tests/YMatterTypeTests/Helpers/Typography+YMatterTypeTests.swift
- Tests/YMatterTypeTests/Typography/Typography+FontTests.swift
- Tests/YMatterTypeTests/Typography/Typography+MutatorsTests.swift
- Tests/YMatterTypeTests/Typography/Typography+SystemTests.swift
If we're building tvOS apps with UIKit, we could use YMatterType to add accessibility features.
Add tvOS support
* Exclude functionality that does not compile for tvOS
* Exclude tests for Dynamic Type changes (not currently supported on iOS)
* Modify tests to use fonts available on both iOS and tvOS platforms
* Fix linter whitespace warnings
* tvOS does not currently support Dynamic Type scaling (even though at the compiler level it does)
* tvOS has some different behaviors around `UITextField` that needed to be accounted for
* tvOS includes a different (smaller) list of fonts than iOS
* not sure why the linter decided to complain about whitespace on otherwise empty lines. New version of SwiftLint?
> Add tvOS support

- Sources/YMatterType/Typography/Typography.swift
Fixed typo in documentation comments for both of the Typography initializers.
This fix is to prevent misinformation to the reader  https://github.com/yml-org/YMatterType/issues/15 
old text -> ///   - chaacterSpacing: letter spacing to use (defaults to `0`)
new text -> ///   - letterSpacing: letter spacing to use (defaults to `0`)
// Optional sections
Any discussion about approach, challenges, etc. that you feel is relevant.
Call out any known issues that are purposely not addressed in this pull request.
For UI work, please include before/after screenshots hosted in a 2-column table for easy side-by-side comparison.
Same as Screenshots above.
> Fix typo in Typography initializers

- README.md
- Sources/YMatterType/Elements/Representables/TypographyLabelRepresentable.swift
- Sources/YMatterType/Elements/TextStyleLabel.swift
- Tests/YMatterTypeTests/Elements/TextStyleLabelTests.swift
Create TextStyleLabel component.
Allow TypographyLabel with a single line to be used within SwiftUI. Issue #55 
Added new file `TextStyleLabel.swift` and updated the README.md
**Unit Tests:** Apple doesn’t provide any testing framework for SwiftUI yet or a way to have UI test within a Swift Package. Since the solution to include unit tests for this component is not straightforward, I'll create a separate PR for it.
Apologies for the bad quality (10MB limit issue):
https://user-images.githubusercontent.com/122470090/214679564-69af0895-218e-40a1-ae92-ee17fb35ee48.mov
> [SwiftUI] Add TextStyleLabel #55

- .swiftlint.yml
The console output from SwiftLint is complaining about two of our rules, which are either not applied or are obsolete. So we're removing them.
Resolve SwiftLint warnings about unused/obsolete rules (Fix #58)
Update `.swiftlint.yml` config file
Need to apply these changes to all of our open source repos
Both unit test and documentation coverage are unchanged.
> [58] Fix swiftlint config warnings

- Sources/YMatterType/Typography/FontFamily/DefaultFontFamilyFactory.swift
- Sources/YMatterType/Typography/FontFamily/FontFamily.swift
- Sources/YMatterType/Typography/FontFamily/HelveticaNeueFontFamily.swift
- Tests/YMatterTypeTests/Typography/FontFamily/DefaultFontFamilyFactoryTests.swift
- Tests/YMatterTypeTests/Typography/FontFamily/FontFamilyTests.swift
- Tests/YMatterTypeTests/Typography/FontFamily/HelveticaNeueFontFamilyTests.swift
- Tests/YMatterTypeTests/Typography/FontFamily/SystemFontFamilyTests.swift
HelveticaNeue is installed on iOS (and tvOS) devices. It has some quirks that mean we can't just use a DefaultFontFamiy for it, so a custom `FontFamily` implementation is needed.
Add a font family implementation for HelveticaNeue that handles both regular and italic.
Fix #60 
* Minor change to behavior of FontFamily to handle naming fonts where there is no weight name
* Added new font family implementation
* Modified DefaultFontFamilyFactory to handle HelveticaNeue case.
* Unit tests
**97.9%**
**100%**
> [Issue-60] Add HelveticaNeue font family

- Sources/YMatterType/Typography/FontFamily/SystemFontFamily.swift
- Sources/YMatterType/Typography/Typography+Font.swift
- Tests/YMatterTypeTests/Typography/FontFamily/SystemFontFamilyTests.swift
`FontFamily` moves to the next heavier weight when accessibility bold text is enabled (or the trait collections specify the `.bold` legibility weight), but the built-in Apple system font does this as well, so we ended up making typographies using the `SystemFontFamily` extra bold.
For system font family only we should not manually increase the weight to be used.
Fix #63 `SystemFontFamily` to not increase the weight twice.
* Fix `SystemFontFamily`
* Adjust `Typography+Font.swift` to consider special case of system font
* Add unit test coverage
Our default behavior is to increase the font weight by 100 when accessibility bold text is enabled.
The system font increases the lightest 3 weights by 100, but the remaining weights by 200 each (up to a maximum of 900), so I updated …
> [Issue 63] Don’t manually increase weight of scaled system fonts

- Sources/YMatterType/Typography/TypographyLayout.swift
- Tests/YMatterTypeTests/Typography/TypographyLayoutTests.swift
This currently private method on `TypographyLayout` could be used to style any UIKit view that allows you to set default text attributes.
Fix #69: Make this method public, give it sensible defaults, cover it in documentation comments, and unit tests.
* Modify TypographyLayout
* Add unit tests
Also fixes #66: which were documentation comments for sibling methods in `TypographyLayout`.
97.9%
100%
> [Issue-69] Make buildAttributes public

- Sources/YMatterType/Typography/Typography+Enums.swift
- Tests/YMatterTypeTests/Typography/Typography+EnumTests.swift
Figma exports text style weights as strings. To automate the creation of `Typography` objects from tokens, we need to be able to map from `String` to `Typography.FontWeight`.
Fix #64 Add a failable initializer to `Typography.FontWeight` that accepts a `String`.
* Add new `init?` method to `FontWeight` enum
* Add unit tests
We need this for Figma token automation.
97.9%
100%
> [Issue-64] Initialize FontWeight from string

- Sources/YMatterType/Typography/Typography+Enums.swift
- Tests/YMatterTypeTests/Elements/TypographyButtonTests.swift
- Tests/YMatterTypeTests/Elements/TypographyLabelTests.swift
- Tests/YMatterTypeTests/Elements/TypographyTextFieldTests.swift
- Tests/YMatterTypeTests/Elements/TypographyTextViewTests.swift
- Tests/YMatterTypeTests/Typography/TypogaphyTests.swift
While working on another issue, I noticed that some unit tests would fail if the device (or simulator) the tests were running on had the Accessibility Bold Text feature enabled.
Fix #68 Clean up the unit tests so that they pass whether Bold Text is enabled or not.
* Changes to test cases only
This wasn't affecting CI/CD or anything because those simulators don't have Bold Text enabled, but it is a flakiness that should be cleaned up and will help ensure that our code is robust.
Remains unchanged at 97.9% (didn't anticipate any code coverage changes since I didn't add or remove any tests, only provided different font families to test).
Documentation coverage remains unchanged at 100% because this PR only affects unit test cases.
> [Issue-68] Fix unit tests that fail in Bold Text mode

- Sources/YMatterType/Elements/Representables/TypographyLabelRepresentable.swift
- Sources/YMatterType/Elements/TextStyleLabel.swift
- Tests/YMatterTypeTests/Elements/Representables/TypographyLabelRepresentableTests.swift
- Tests/YMatterTypeTests/Elements/TextStyleLabelTests.swift
- Tests/YMatterTypeTests/Helpers/XCTestCase+TypographyEquatable.swift
The two files that implement our SwiftUI version of typography label did not have good unit test coverage. That's because for `View` you're not supposed to directly call `body` from your unit tests. The same applies to `UIViewRepresentable` and `makeUIView(context:)` and `updateUIView(uiView:context:)` (also we don't have a context to pass in unit tests).
What we can do though is extract the majority of the body of these methods to separate methods that we _can_ test.
Fix #74 Refactor `TextStyleLabel` and `TypographyLabelRepresentable` to be more testable, and then add the tests.
* Refactor `TextStyleLabel`
* Refactor `TypographyLabelRepresentable`
* Add unit tests
In addition to extracting the main bulk of `TextStyleLabel.body` and `TypographyLabelRepresentable.makeUIView()` and …
> Increase test coverage for TextStyleLabel and TypographyLabelRepresentable

- Sources/YMatterType/Extensions/Foundation/String+textSize.swift
- Tests/YMatterTypeTests/Extensions/Foundation/String+textSizeTests.swift
Add method to get text size with given typography. 
A new method is added to provide user the access of size of the text.
Fix https://github.com/yml-org/YMatterType/issues/65
A public method that gives user size of the text.
~99% code coverage.
100% documentation of public APIs.
> [CM-1267] String size calculation

- Sources/YMatterType/Typography/Typography+Font.swift
- Sources/YMatterType/Typography/Typography+Mutators.swift
- Sources/YMatterType/Typography/Typography.swift
- Tests/YMatterTypeTests/Typography/TypogaphyTests.swift
- Tests/YMatterTypeTests/Typography/Typography+FontTests.swift
- Tests/YMatterTypeTests/Typography/Typography+MutatorsTests.swift
We support setting a maximum scale factor on individual UI elements (buttons, labels, text fields, etc.) but not at the Typography label. If there is an app-wide requirement for a given maximum scale factor (e.g. `2.5`) then it would be onerous to apply because every single label, button, etc would need to set that maximum scale factor. It might be nice to be able to set this at the Typography level and then it would apply to every UI element that makes use of that Typography.
Fix #76 Add `maximumScaleFactor` property to `Typography`
* Add property to `Typography`
* Add new mutator to `Typography`
* Adjust behavior of `Typography.generateLayout`
* Add unit tests
I decided that the maximum scale factor should be the minimum of the limit set by the individual UI element (if any) and the …
> [Issue 76] Add maximumScaleFactor to Typography

- Sources/YMatterType/Typography/FontFamily/FontFamily.swift
- Sources/YMatterType/YMatterType+Logging.swift
- Tests/YMatterTypeTests/Typography/TypogaphyTests.swift
- Tests/YMatterTypeTests/YMatterType+LoggingTests.swift
Add centralised logging.
Adding centralized logging by extending `Typography`.
Fix https://github.com/yml-org/YMatterType/issues/78
Any change in functionality is out of scope.
~99% code coverage.
100%
> [CM-1316] Added cetralized logging
